name: brainconcent_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  smooth_page_indicator: ^1.0.0+2
  flutter_screenutil: ^5.5.4
  form_field_validator: ^1.1.0
  http: ^0.13.5
  provider: ^6.0.4
  lottie: ^1.4.3
  flutter_secure_storage: ^4.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  internet_connection_checker: ^0.0.1+3
  get_it: ^7.2.0
  shared_preferences: ^2.0.0
  dartz: ^0.10.1
  google_fonts: ^3.0.1
  pin_code_fields: ^7.4.0
  video_player: ^2.4.7
  chewie: ^1.3.5
  carousel_slider: ^4.1.1
  just_audio: ^0.9.18
  image: ^3.1.3
  audio_session: ^0.1.0
  rive: ^0.9.1
  shimmer: ^2.0.0
  flip_card: ^0.6.0
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/icons/app/
    - assets/icons/puzzle/
    - assets/images/app/
    - assets/images/onboarding/
    - assets/images/authentication/
    - assets/images/avatar/
    - assets/images/games/
    - assets/images/stories/
    - assets/images/animals/
    - assets/rive/winner.riv
    - assets/sounds/animals/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf

    - family: PuzzleIcons
      fonts:
        - asset: assets/icons/puzzle/PuzzleIcons.ttf
