name: brainconcent_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  smooth_page_indicator: ^1.0.0+2
  flutter_screenutil: ^5.5.4
  form_field_validator: ^1.1.0
  http: ^0.13.5
  provider: ^6.0.4
  lottie: ^1.4.3
  iconsax: ^0.0.8
  flutter_secure_storage: ^6.0.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  internet_connection_checker: ^0.0.1+3
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  dartz: ^0.10.1
  google_fonts: ^3.0.1
  pin_code_fields: ^7.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/json/
    - assets/svg/app/
    - assets/icons/app/
    - assets/images/app/
    - assets/images/onboarding/
    - assets/svg/authentication/
    - assets/icons/authentication/
    - assets/images/authentication/
    - assets/images/avatar/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
